name: Upwork Job Fetcher

on:
  schedule:
    - cron: "*/30 * * * *"  # runs every 30 minutes
  workflow_dispatch:  # allow manual run

jobs:
  fetch_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Create Python script
        run: |
          cat << 'EOF' > upwork_fetch.py
          import os
          import requests
          import smtplib
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart

          UPWORK_TOKEN = os.getenv("UPWORK_TOKEN")
          EMAIL_USERNAME = os.getenv("EMAIL_USERNAME")
          EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
          RECIPIENT_EMAIL = os.getenv("RECIPIENT_EMAIL")

          url = "https://www.upwork.com/api/graphql/v1?alias=mostRecentJobsFeed"
          headers = {
              "x-upwork-api-tenantid": "1580817095745536001",
              "referer": "https://www.upwork.com/nx/find-work/most-recent",
              "authorization": f"Bearer {UPWORK_TOKEN}",
              "Content-Type": "application/json",
          }
          body = {
              "query": """
              query($limit: Int, $toTime: String) {
                mostRecentJobsFeed(limit: $limit, toTime: $toTime) {
                  results {
                    id
                    title
                    description
                    client {
                      location { country }
                    }
                  }
                }
              }""",
              "variables": {"limit": 5},
          }

          response = requests.post(url, headers=headers, json=body)
          data = response.json()
          jobs = data.get("data", {}).get("mostRecentJobsFeed", {}).get("results", [])

          html_content = "<h2>Recent Upwork Jobs</h2>"
          for job in jobs:
              title = job.get("title", "No title")
              desc = job.get("description", "No description")
              country = job.get("client", {}).get("location", {}).get("country", "Unknown")
              html_content += f"<p><strong>{title}</strong><br>{desc}<br><em>{country}</em></p>"

          msg = MIMEMultipart("alternative")
          msg["Subject"] = "Upwork Job Feed"
          msg["From"] = EMAIL_USERNAME
          msg["To"] = RECIPIENT_EMAIL
          msg.attach(MIMEText(html_content, "html"))

          with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
              server.login(EMAIL_USERNAME, EMAIL_PASSWORD)
              server.sendmail(EMAIL_USERNAME, RECIPIENT_EMAIL, msg.as_string())
          print("✅ Email sent successfully!")
          EOF

      - name: Run Python script
        env:
          UPWORK_TOKEN: ${{ secrets.UPWORK_TOKEN }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python upwork_fetch.py
